### PR TITLE
Hitscan auto vacc logic //somewhat

### PR DESCRIPTION
**Pull request by NitroTF2**
yeaaaaaa no body wanted to do it so i did it

### CODE REVIEW

**Comment by frel0** [comment]
u like wasting charges do you..?

**Comment by carvee** [comment]
u like wasting charges do you..?

**Comment by NitroTF2** [comment]
sorry dude i made this for hvh, and it has logic. it won't charge if they have bonk in the hand or they are on bonk cond.. 
and melee so please don't mald.. this is for casual not hvh

**Comment by frel0** [comment]
most of the fware users play hvh too... i disagree with this shit so much..

**Comment by johnathon-walnut** [comment]
I'm not merging while you have n-bombs in the code

**Comment by NitroTF2** [comment]
> I'm not merging while you have n-bombs in the code

i am trolling oomfie..

**Comment by xxmyn** [comment]
@frel0 @NitroTF2 can you check the changes i've made and i'll merge if;
A) they work
B) you're fine with it

**Pull request merged**
