### PR TITLE
Projectile NoSpread

### PR DESCRIPTION
**Pull request by TheGameEnhancer2004**
str8 from cathook!!
Also, it doesn't break the dt)))

### CODE REVIEW

**Comment by swamptwink** [comment]
Why were these all done with github web?

**Comment by TheGameEnhancer2004** [comment]
> Why were these all done with github web?
i dont have enough space on my pc for the github desktop

**Comment by swamptwink** [comment]
Ahh, you can actually use [github in visual studio](https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md) if you don't have space for the gh desktop app, if you want your commits signed you can also set that up through visual studio.

**Comment by TheGameEnhancer2004** [comment]
> Ahh, you can actually use [github in visual studio](https://github.com/github/VisualStudio/blob/master/docs/getting-started/authenticating-to-github.md) if you don't have space for the gh desktop app, if you want your commits signed you can also set that up through visual studio.

Oh, alright

**Pull request merged**
