### PR TITLE
fix for demo

### PR DESCRIPTION
**Pull request by stax132349**
the cheat tries to shoot at enemies with pills even though the pill will explode before hitting them, based off of my testing this works how i expected now

### CODE REVIEW

**Comment by johnathon-walnut** [comment]
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by johnathon-walnut** [comment]
Please explain the `m_flPredictionTime;` lines

**Comment by stax132349** [comment]
i dont fucking know

**Comment by stax132349** [comment]
i dont know how to code i thought it was needed remove it if you want

**Comment by johnathon-walnut** [comment]
What

**Comment by stax132349** [comment]
well thanks for telling me

**Comment by stax132349** [comment]
i only did this because the cheat shoots when the pills will explode before hitting them

**Comment by johnathon-walnut** [comment]
ok well it wont reset back to the chosen value on weapons that dont do that

**Comment by stax132349** [comment]
good to know

**Comment by stax132349** [comment]
this is basically just a suggestion at this point

**Pull request closed without merging**
