### PR TITLE
Halloween Footsteps + fix for particle colors

### PR DESCRIPTION
**Pull request by stax132349**
credits go to mfed for the code

### CODE REVIEW

**Comment by AscendedSion** [comment]
DO NOT. merge this PULL REQUEST.

**Comment by stax132349** [comment]
faggot

**Comment by AscendedSion** [comment]
fuck you paster!

**Comment by imgladnotu** [comment]
paster esex conversation above

**Comment by BLS01** [comment]
i told ya particle colors were not working  😡😡😡😡😡😡😡😡 but you niggas wont fucking listen

**Comment by stax132349** [comment]
it was because i never realized that i didnt include it

**Comment by stax132349** [comment]
well now it works so be happy!

**Comment by Eniac763** [comment]
mfed is on maternity leave

**Comment by imgladnotu** [comment]
> mfed is on maternity leave

mpreg

**Comment by AscendedSion** [comment]
guys im preggy

**Comment by imgladnotu** [comment]
> guys im preggy

no, ur fat

**Comment by johnathon-walnut** [comment]
I love feet

**Pull request merged**
