### PR TITLE
Added Lua API

### PR DESCRIPTION
**Pull request by lnx00**
Added a Lua API that allows external scripts to be loaded and interact with the game.
The API currently supports a few basic callbacks and classes to create simple scripts. But the structure of the Lua engine allows for easy modification and addition of new interfaces, classes and types and more.

Documentation for Lua can be found here: https://fedoraware.github.io/Docs/Lua/

### CODE REVIEW

**Comment by johnathon-walnut** [comment]
Will this compile on actions?

**Comment by lnx00** [comment]
I sure hope it does. I tried to integrate the Lua and sol2 libraries as good as possible to prevent any problems, so I guess it will work

**Comment by johnathon-walnut** [comment]
Fuck it lets goooooooo

**Comment by lnx00** [comment]
It compiled :D

**Comment by johnathon-walnut** [comment]
Wholesome

**Comment by AscendedSion** [comment]
OH MY GOD - Brian, family guy

**Comment by N1kolasFlaV** [comment]
cant wait for rijin v3 to have lua api :D

**Comment by yujispin990** [comment]
lets gooooo!

**Pull request merged**
