### PR TITLE
Fix the broken chams menu. (important)

### PR DESCRIPTION
**Pull request by PiantaMK**
the 2 chams menus dont like being in the same column it seems.

### CODE REVIEW

**Review by lnx00 — CHANGES_REQUESTED** [review]
This is a workaround and doesn't fix the actual issue. There's probably a name conflict with one of the items.

Names must be unique in the same context when working with ImGui.

**Comment by swamptwink** [comment]
not a fan of your indentation frend

**Comment by skibiditoiletfan2007** [comment]
could you put this through chatgpt and make it fix the indentation

**Comment by swamptwink** [comment]
why would you do that

**Comment by skibiditoiletfan2007** [comment]
its easy its free its take little to no time and it works

**Comment by swamptwink** [comment]
this kermit was made from my iphone! [buy an iphone today!](https://www.apple.com)

**Comment by PiantaMK** [comment]
also fixed some color pickers i was too blind to see for over a week

**Pull request merged**
