### PR TITLE
DO MATH 4 - 70% = 1.2

### PR DESCRIPTION
**Pull request by faoktjba42laf**

### CODE REVIEW

**Comment by xxmyn** [comment]
charge is a percent between 0 and 1

**Comment by xxmyn** [comment]
ohh nvm i see what this does

**Comment by faoktjba42laf** [comment]
Literally max charge by SDK on sticky is 4 so 
4 - 70% decreased charge = 1.2.

**Comment by xxmyn** [comment]
alr then

**Pull request merged**
