### PR TITLE
Create new sig for renderspritecard

### PR DESCRIPTION
**Pull request by HutchyBen**
This sig DOES work!!! is this the only sig that had weird not found issue i cant find issue that doesnt have it?

### CODE REVIEW

**Comment by HutchyBen** [comment]
why even was wildcards there it works without or am i beign goofy

**Comment by HutchyBen** [comment]
yers they are not even needed i stared at the asembylers

**Comment by lnx00** [comment]
I don't see how this is better, since the signature with wildcards is unique and correct 🤔

Some of the wildcards are there to make the signature resistant to small code changes. For example `83 EC 28` (`sub esp, 28`) should use a wildcard for the `28`, so the signature still works if they decide to add/remove local variables in the function.

**Comment by HutchyBen** [comment]
That is fair.

**Pull request closed without merging**
