### PR TITLE
dont waste charges

### PR DESCRIPTION
**Pull request by frel0**

### CODE REVIEW

**Comment by xxmyn** [comment]
i hate this.

**Comment by johnathon-walnut** [comment]
Wtf is the point of this?

**Comment by johnathon-walnut** [comment]
Surely this only accounts for heavy? Why not do maxhealth - 90 to account for critical flares

**Comment by frel0** [comment]
why should it just waste charges when a heavy can kill a fucking pyro in like less than 1.5 seconds
and pyro does low dmg..

**Pull request merged**
