### PR TITLE
draggable spec list fix + outline

### PR DESCRIPTION
**Pull request by AscendedSion**
yippee 
if you dont accept this you support mfed's pregnancy

### CODE REVIEW

**Comment by Eniac763** [comment]
who's the father tho

**Comment by hyperventilation** [comment]
countryhack leak

**Comment by imgladnotu** [comment]
> who's the father tho

unfortunately there's like multiple different people who has been inside mfed so we don't know

**Comment by AscendedSion** [comment]
> countryhack leak

dont tell them

**Pull request closed without merging**
