### PR TITLE
Hitscan no spread

### PR DESCRIPTION
**Pull request by TheGameEnhancer2004**
Not sure if it works correctly, but at least the game doesnt crash.
Also for some reason it takes 1 dt tick away, so you can only use max 20 ticks

### CODE REVIEW

**Comment by lnx00** [comment]
Epic, I hope this works!

**Comment by Muffinmaker2** [comment]
HUUUUUUUUUUUUH NO SPREAD HITSCAN OWOOAJO%RNJO=?JNQ=RIOPFNWMgtewos0i4pzhnmrptorfz

**Comment by c043** [comment]
does this work with projectile???? im new to fedoraware

**Comment by TheGameEnhancer2004** [comment]
> does this work with projectile???? im new to fedoraware

The projectile nospread is already in the cheat. This one is for hitscan weapons

**Comment by swamptwink** [comment]
works well fren :D

**Pull request merged**
