### PR TITLE
autovacc fix

### PR DESCRIPTION
**Pull request by debugac**
for blast...

### CODE REVIEW

**Comment by johnathon-walnut** [comment]
Are you stupid

**Comment by debugac** [comment]
> 

yes, yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes,

**Comment by debugac** [comment]
actually no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no.no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no. no.

**Comment by debugac** [comment]
nvm, yes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yesyes,  yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by johnathon-walnut** [comment]
This PR is stupid

**Comment by debugac** [comment]
𝓷𝓸 𝓲𝓽𝓼 𝓷𝓸𝓽

**Comment by johnathon-walnut** [comment]
Learn C++

**Comment by debugac** [comment]
𝔫𝔦𝔤𝔤𝔞?

**Comment by N1kolasFlaV** [comment]
tbh frelo is a selfcoder boss slovakian and mfart is pastor asf...

**Comment by xxmyn** [comment]
what a joke, ill do this properly when i care 🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️

**Comment by imgladnotu** [comment]
mfw cant right click and press r

**Comment by lnd1g0** [comment]
> mfw cant right click and press r

look at how he types bro, hes clearly crippled...

**Pull request closed without merging**
