### PR TITLE
i think you missed something frel0..

### PR DESCRIPTION
**Pull request by NitroTF2**
added sentry rockets..

### CODE REVIEW

**Comment by frel0** [comment]
i wouldnt like the sentry rockets to waste my ubercharges mr. fourteen.

**Comment by lnx00** [comment]
hmmmm

**Comment by frel0** [comment]
id make a dropdown and make you choose what do you want to react to.

**Comment by NitroTF2** [comment]
question to you frel0 do you want your heavy to get hurt by the sentry rockets? yk you can get that charge fast, it won't hurt at all

**Comment by frel0** [comment]
image
are you blind you fat faggot

**Comment by carvee** [comment]
NIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGER

**Pull request merged**
