### PR TITLE
Multipoint changes.

### PR DESCRIPTION
**Pull request by xxmyn**
- Added the ability to use "Adaptive-Multipoint" where points are randomly created for each hitbox each tick.
- Fixed an issue with static multipoint points not including one corner
- Moved transforms and other things to their own functions
- Closes #1047

### CODE REVIEW

**Comment by AscendedSion** [comment]
do you honestly think you're fucking funny

**Comment by xxmyn** [comment]
> do you honestly think you're fucking funny

what

**Comment by AscendedSion** [comment]
> what
poop

**Comment by AscendedSion** [comment]
> > do you honestly think you're fucking funny
> 
> what

poop

**Pull request merged**
