### PR TITLE
Fixed crithack and more

### PR DESCRIPTION
**Pull request by lnx00**
- Fixed crithack completely
- Added linux support
- Some minor improvents and fixes

### CODE REVIEW

**Comment by lnx00** [comment]
:trollface:

**Comment by johnathon-walnut** [comment]
i hate LiNuX

**Comment by lnx00** [comment]
:(

**Comment by Capybaron** [comment]
> :(

I love you

**Comment by lnx00** [comment]
:)

**Comment by darkst0rm223** [comment]
>tfw crithack broken forever

**Comment by HARrhhv2** [comment]
no crit hack fix? 🥺🥺

**Comment by AscendedSion** [comment]
i am so fucking sad

**Comment by Capybaron** [comment]
no linuck suppot :(((

**Comment by imgladnotu** [comment]
closed, very not poggers of you mr walnut

**Pull request closed without merging**
