### PR TITLE
Better nopush choices

### PR DESCRIPTION
**Pull request by SylveonBottle**
`if (pCmd->forwardmove == 0 && pCmd->sidemove == 0 && g_EntityCache.GetLocal()->OnSolid())`
This works fine; however, I've noticed that the movement is slower than if nopush was off normally.

`pCmd->buttons & (IN_FORWARD | IN_BACK | IN_MOVERIGHT | IN_MOVELEFT)`
This is more accurate.

And truth be told, I _love_ the slower version. 

I don't want people pushing me out of spawn if possible, but I also don't want to be kicked if I stand still and someone nopush-checks me. So "Slower Idle" is a compromise between nopush and yespush- Players can push you while you're not moving, however the pushing is slower. Not slow enough to raise suspension, but slow enough to make this a valid choice that I feel like many users will pick. You'll be tougher to push out of spawn than normal players, but you _will_ be pushed, which prevents hackusation. 

this also fixes the issue where people not using WASD were fucked
+moved some things around (stop, during, start -> start, during, stop)

### CODE REVIEW

**Comment by SylveonBottle** [comment]
Considering [f388c7c](https://github.com/Fedoraware/Fedoraware/commit/f388c7ca45df0538f6b69bcdba0950f589d0210c) I'm guessing no slow push

**Comment by xxmyn** [comment]
idk maybe i really dislike the afk check tho

**Comment by SylveonBottle** [comment]
I had in-air check because the entire point of idle push (for me adding it at least) was to prevent teammates from pushing you while you're bhopping around, but considering you labeled the entire commit to 'fixing' nopush despite more code being spent on backtrack, I feel like this whole thing annoyed you so I'll just leave it like it is and fix it in my local build.

**Comment by johnathon-walnut** [comment]
Baan is a meanie head I think it was a fine idea

**Comment by xxmyn** [comment]
it was called fixing it cause it didnt compile

**Comment by xxmyn** [comment]
the code was also messy with how it was checking the movement thing, and im pretty sure it didnt work cause if u failed the check the hook would just end and u would have no push

**Pull request closed without merging**
