### PR TITLE
Added "Fix Input Delay".

### PR DESCRIPTION
**Pull request by swamptwink**
Not sure what it does but mfed said I should add it, so I did that.

### CODE REVIEW

**Comment by swamptwink** [comment]
"eurgh but sig too long" okay well when sig was shorter it crashed on inject so deal with it 😈

**Comment by GC634** [comment]
I think what this does is when you have your graphics high up, and you lag. This code is what fixes it, not sure if that's the case tho.

**Comment by canedoly** [comment]
> I think what this does is when you have your graphics high up, and you lag. It fixes the lag. This is what the code does, not sure if that's the case tho.

no, in jengaware this helps with inconsistency with game stuff

**Comment by swamptwink** [comment]
dont try to guess it's a waste of time NOBODY KNOWS WHAT THIS DOES!

**Comment by GC634** [comment]
> dont try to guess it's a waste of time NOBODY KNOWS WHAT THIS DOES!

( ͡° ͜ʖ ͡°)

**Pull request merged**
