### PR TITLE
pretty much this sig is shorter so its way cooler

### PR DESCRIPTION
**Pull request by HutchyBen**

### CODE REVIEW

**Comment by lnx00** [comment]
A three byte signature? And it's unique?

Btw: wildcards at the end of a signature don't really make sense, as they will always match if the last non-wildcard byte was a match, making them redundant.

**Comment by HutchyBen** [comment]
> A three byte signature? And it's unique?
> 
> Btw: wildcards at the end of a signature don't really make sense, as they will always match if the last non-wildcard byte was a match, making them redundant.

yep its unique. i like wildcards at end

**Comment by HutchyBen** [comment]
image
the truths.

**Comment by lnx00** [comment]
Unbelievable

**Pull request merged**
