### PR TITLE
Resolver recode

### PR DESCRIPTION
**Pull request by xxmyn**
Major changes include;
-A working, non pasted resolver.
-Using confirmed player pitches for up to a second before marking them as stale (as long as they weren't random)
-Fake pitch & 180 yaw on shot working properly.
-Resolver can now find a players real pitch while they are firing even if they are attempting to fake it.
-Resolver no longer attempting to resolve players who are firing their weapons and cannot be anti aiming.
-Added an option to turn off resolver on in-air players
-Switched resolver to use animstate as well as eye angles

### CODE REVIEW

**Comment by xDroflLOL** [comment]
that's a lot

**Comment by lnx00** [comment]
The resolver wasn't pasted 😡

**Comment by xxmyn** [comment]
> The resolver wasn't pasted 😡

wait srsly, i thought it was just the cathook resolver

**Comment by lnx00** [comment]
> > The resolver wasn't pasted 😡
> 
> wait srsly, i thought it was just the cathook resolver

No, I only took the array of angles that it cycles through from cathook

**Comment by johnathon-walnut** [comment]
So it's pasted then.,.,.,..,
,.,

**Pull request merged**
