### PR TITLE
Visual configs

### PR DESCRIPTION
**Pull request by HutchyBean**
Tab buttons look a little bit naff so someone who knows how to properly imgui could make them nicer but like everything works

can someone also double check if all the loads and saves are correct

### CODE REVIEW

**Comment by xxmyn** [comment]
ill test & merge when i get home if nobody else has

**Comment by HutchyBean** [comment]
Just did some thinking and the back up of configs probably isn't working l0l

**Comment by HutchyBean** [comment]
Uhh I'll fix in like 8 hours when I'm finished with work or if you wanna look into my poo you can fix it

**Comment by HutchyBean** [comment]
I'm a double moron second thinking again you can just copy all the existing configs to the visuals folder instead of loading them and saving them

**Pull request closed without merging**
