### PR TITLE
FUCK OFF LUA!!!

### PR DESCRIPTION
**Pull request by HutchyBean**

### CODE REVIEW

**Comment by cheeseliker42** [comment]
true

**Comment by imgladnotu** [comment]
> but how will lovense support be extended without lua?!?!

hardcode it

**Comment by imgladnotu** [comment]
> 

oh no what ever will the cringey gay csgo cheaters that decided to play tf2 ever gonna do now!?!?!!/?!/???!>??1??1/?

**Comment by lnx00** [comment]
i love lua

**Comment by HutchyBean** [comment]
Admin abuse

**Comment by lnx00** [comment]
> you're absolutely right, i love lua too and it should definitely not be removed even though nobody uses it!

true

**Pull request merged**
